# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Mvcswap Wallet CI

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Enable Corepack (Yarn)
        run: corepack enable

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        env:
          CI: false
        run: yarn build

      # TODO: enable tests after stabilizing current test suite
      # - name: Test
      #   run: yarn test --watchAll=false

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          ssh-key: ${{ secrets.MVCSWAP_DEPLOY_KEY }}
          branch: gh-page
          repository-name: mvc-swap/wallet.mvcswap.com
